#!/bin/bash
#SBATCH -n 4                 
#SBATCH -N 1                 
#SBATCH --mem=24G                     
#SBATCH -p a40               
#SBATCH --qos=q_a40          
#SBATCH --account=ga40       
#SBATCH --job-name=closed_set_imagenet
#SBATCH --output=../logs/out.log  
#SBATCH --gres=gpu:1

python evaluate_taxonomy_labeling.py \
    --dataset imagenet \
    --data_dir /home/pmonserrat/datasets/imagenet/extracted_data \
    --model_family qwen \
    --model_name  Qwen/Qwen3.5-0.8B \
    --batch_size 16 \
    --max_samples 500 \
    --verbose \